services:
  frontend:
    image: anguspllg/tisseo:latest
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./config:/app/config
